export const imageQueryStrings: string[] = [
  "Looney Tunes",
  "Fuck",
  "Award",
  "New Year's Day",
  "O. J. Simpson",
  "Genghis Khan",
  "Typhoon Maysak (2015)",
  "Gautama Buddha",
  "Jesus",
  "Drinking_from_shoes",
  "Quo_vadis?",
  "Vin Diesel",
  "Wendy Williams",
  "Lil Nas X",
  "Piers Morgan",
  "David Dobrik",
  "James Charles",
  "World War I",
  "Helianthus",
  "Logger Butte",
  "Pope Francis",
  "Super Mario",
  "Billie Eilish",
  "Justin Bieber",
  "The Weeknd",
  "Britney Spears",
  "Egyptian_pyramids",
  "Television",
  "Radio",
  "Mobile_phone",
  "Airplane",
  "Car",
  "Horse",
  "Train",
  "Apollo",
  "Apollo 4",
  "Apollo 8",
  "Apollo 11",
  "Apollo 14",
  "Internet",
  "Telephone",
  "Newspaper",
  "Evil",
  "Sexual_intercourse",
  "Condom",
  "Pregnancy",
  "Strap-on_dildo",
  "Mullet (haircut)",
  "Ozzy Osbourne",
  "Mark Zuckerberg",
  "Joe Rogan",
  "Joe Biden",
  "Tucker Carlson",
  "Psilocybin mushroom",
  "Baseball",
  "Basketball",
  "Football",
  "Police",
  "SWAT",
  "Big Bang",
  "Cannabis",
  "Observable universe",
  "Red",
  "Black",
  "Neil deGrasse Tyson",
  "Donald Trump",
  "Camera",
  "Human",
  "Evil",
  "Devil",
  "God",
  "Angel",
  "Truth",
  "Dolly Parton",
  "Jesus",
  "Pornography",
  "Kanye West",
  "Marilyn Monroe",
  "Elvis Presley",
  "Barbie",
  "IPhone",
  "Racing",
  "Blobject",
  "Furniture",
  "Tamagotchi",
  "Earth",
  "Mars",
  "USS Doherty (DE-14)",
  "Gaten Matarazzo",
  "Memory management controller",
  "Homosexuality in China",
  "Socks and sandals",
  "Heterodontosaurus",
  "Karate",
  "United States invasion of Grenada",
  "CMLL World Middleweight Championship",
  "Saint Anne",
  "Gopnik",
  "Interservice rivalry",
  "SPP-1 underwater pistol",
  "Chocolate bloom",
  "Sloth bear",
  "Willie Nelson",
  "Lambda phage",
  "Florence Y'all Water Tower",
  "Embryo space colonization",
  "Moon landing conspiracy theories",
  "Black hairy tongue",
  "Animals in space",
  "Chick sexing",
  "Toilets in Japan",
  "Gurn",
  "The Headington Shark",
  "Electroencephalophone",
  "Competitive eating",
  "Diet Coke and Mentos eruption",
  "Pillow Fight League",
  "Rabbit show jumping",
  "Nuclear weapon",
  "Volcano",
  "Church of Scientology",
  "Galaxy",
  "On the Mindless Menace of Violence",
  "Novaya Zemlya effect",
  "Scottish_Fold",
  "Recreational drug use",
  "Whisky",
  "Cigarette",
  "Coffee",
];
