export const imageQueryStrings: string[] = [
  "Looney Tunes",
  "Fuck",
  "Award",
  "New Year's Day",
  "O. J. Simpson",
  "Genghis Khan",
  "Typhoon Maysak (2015)",
  "Gautama Buddha",
  "Jesus",
  "Drinking_from_shoes",
  "Quo_vadis?",
  "Vin Diesel",
  "Wendy Williams",
  "Lil Nas X",
  "Piers Morgan",
  "David Dobrik",
  "James Charles",
  "World War I",
  "Helianthus",
  "Logger Butte",
  "Pope Francis",
  "Super Mario",
  "Billie Eilish",
  "Justin Bieber",
  "The Weeknd",
  "Britney Spears",
  "Egyptian_pyramids",
  "Television",
  "Radio",
  "Mobile_phone",
  "Airplane",
  "Car",
  "Horse",
  "Train",
  "Apollo",
  "Apollo 4",
  "Apollo 8",
  "Apollo 11",
  "Apollo 14",
  "Internet",
  "Telephone",
  "Newspaper",
  "Evil",
  "Sexual_intercourse",
  "Condom",
  "Pregnancy",
  "Strap-on_dildo",
  "Mullet (haircut)",
  "Ozzy Osbourne",
  "Mark Zuckerberg",
  "Joe Rogan",
  "Joe Biden",
  "Tucker Carlson",
  "Psilocybin mushroom",
  "Baseball",
  "Basketball",
  "Football",
  "Police",
  "SWAT",
  "Big Bang",
  "Cannabis",
  "Observable universe",
  "Red",
  "Black",
  "Neil deGrasse Tyson",
  "Donald Trump",
  "Camera",
  "Human",
  "Evil",
  "Devil",
  "God",
  "Angel",
  "Truth",
  "Dolly Parton",
  "Pornography",
  "Kanye West",
  "Marilyn Monroe",
  "Elvis Presley",
  "Barbie",
  "IPhone",
  "Racing",
  "Blobject",
  "Furniture",
  "Tamagotchi",
  "Earth",
  "Mars",
  "USS Doherty (DE-14)",
  "Gaten Matarazzo",
  "Memory management controller",
  "Homosexuality in China",
  "Socks and sandals",
  "Heterodontosaurus",
  "Karate",
  "United States invasion of Grenada",
  "CMLL World Middleweight Championship",
  "Saint Anne",
  "Gopnik",
  "Interservice rivalry",
  "SPP-1 underwater pistol",
  "Chocolate bloom",
  "Sloth bear",
  "Willie Nelson",
  "Lambda phage",
  "Florence Y'all Water Tower",
  "Embryo space colonization",
  "Moon landing conspiracy theories",
  "Black hairy tongue",
  "Animals in space",
  "Chick sexing",
  "Toilets in Japan",
  "Gurn",
  "The Headington Shark",
  "Electroencephalophone",
  "Competitive eating",
  "Diet Coke and Mentos eruption",
  "Pillow Fight League",
  "Rabbit show jumping",
  "Nuclear weapon",
  "Volcano",
  "Church of Scientology",
  "Galaxy",
  "On the Mindless Menace of Violence",
  "Novaya Zemlya effect",
  "Scottish_Fold",
  "Recreational drug use",
  "Whisky",
  "Cigarette",
  "Coffee",
  "Volkswagen New Beetle",
  "File:Cow-on_pole,_with_antlers.jpeg",
  "File:Unst_Bus_Shelter.jpg",
  "File:Coober_Pedy_Warning_sign_02427.jpg",
  "File:Beghilos.svg",
  "Elon Musk's Tesla Roadster",
  "Bananadine",
  "Rainbow",
  "File:Polydactyly_01_Lhand_AP.jpg",
  "Chicken",
  "Unicycle",
  "Brian's Brain",
  "Beezin'",
  "Erotic photography",
  "Lawnchair Larry flight",
  "Evil clown",
  "Headington Shark",
  "Cool S",
  "Cabazon Dinosaurs",
  "File:Emagicken.jpg",
  "Equestrian statue of the Duke of Wellington, Glasgow",
  "Fire photography",
  "Hellmouth",
  "Knitta Please",
  "Pricasso",
  "Portland International Airport carpet",
  "dice",
  "Fart Proudly",
  "Ossian",
  "File:Walken-Cowbell.jpg",
  "File:Quintephone_brainwave_regen_poster_colour.jpg",
  "Musical saw",
  "Slutwave",
  "File:The_Shaggs.JPG",
  "Monster_movie",
  "Black and white hat symbolism in film",
  "Atari video game burial",
  "File:2_Hours_Doing_Nothing_screenshot.jpg",
  "File:Instagram_egg.jpg",
  "File:Crawl_on_Wikipedia_from_random_article_to_Philosophy..gif",
  "File:Original_Doge_meme.jpg",
  "Ithaa",
  "Ketchup as a vegetable",
  "Pieing",
  "File:RickRoll.png",
  "Artistic roller skating",
  "Bog snorkelling",
  "Extreme ironing",
  "Lawn mower racing",
  "Wellie wanging",
  "Free the nipple",
  "File:Pioneer_plaque_humans.svg",
  "File:GameStop_(14666287269).jpg",
  "File:Xenu_space_plane.jpg",
  "If a tree falls in a forest",
  "File:Starlette.jpg",
  "File:Camp_-_Notes_on_Fashion_at_the_Met_-_Burberry_rainbow_cape_(73854).jpg",
  "File:Plastic_comb,_2015-06-07.jpg",
  "File:Mud_Cow_Racing_-_Pacu_Jawi_-_West_Sumatra,_Indonesia.jpg",
  "File:Falstaff_3.jpg",
  "File:PikiWiki_Israel_13773_AIDA_AT_MASADA_2011.jpg",
  "File:NNC-US-1907-G$20-Saint_Gaudens_(Arabic).jpg",
  "File:Shimano_Hyperglide_cassette_8-speed_CS-HG51_11-32.jpg",
  "File:ANA_soldier_with_RPG-7_in_2013-cropped.jpg",
  "File:Casing.jpg",
  "File:Gas_mask_MUA_IMGP0157.jpg",
  "File:Red_telephone_box,_St_Paul's_Cathedral,_London,_England,_GB,_IMG_5182_edit.jpg",
  "File:Blasting_of_a_chimney_at_the_former_Henninger_Brewery_in_Frankfurt_am_Main,_Germany.jpg",
  "File:Streichholz.jpg",
  "File:Roasted_coffee_beans.jpg",
  "File:Samurai_with_sword.jpg",
  "File:Muybridge_race_horse_animated.gif",
  "File:360_degrees_fogbow.jpg",
  "File:Krilleyekils.jpg",
  "File:HEUraniumC.jpg",
  "File:Mandel_zoom_00_mandelbrot_set.jpg",
  "File:Solar_eclipse_1999_4.jpg",
  "File:Carrots_of_many_colors.jpg",
  "Great Stink",
  "High five",
  "Toilet paper orientation",
  "File:Mayor_Stubbs.jpg",
  "Rubber duck",
  "Emoji",
  "File:Texting_Emoji.jpg",
  "File:BlackMarble20161km.jpg",
  "File:Cat demonstrating static cling with styrofoam peanuts.jpg",
  "Painting",
  "Poverty",
  "File:Juan_Mann.jpg",
  "Rajneesh",
  "Black hole",
  "File:Self_make_up_by_an_artist.jpg",
  "Facial mask",
  "File:Ecstasy_monogram.jpg",
  "File:Man_consults_with_pharmacist.jpg",
  "File:BEATIFUL_CAT.jpg",
  "File:Direction_sign_in_front_of_ghost_train.jpg",
  "File:František_Dostál_Humor_1.jpg",
  "File:František_Dostál_Humor_6.jpg",
  "File:Funny_photo_of_Peng_Yunyue_in_Hsinchu_1940s.jpg",
  "File:Huile_d'argan_004.JPG",
  "File:In_the_Depths_of_Recession_....._-_geograph.org.uk_-_1561673.jpg",
  "File:Kawanabesatou1.jpg",
  "File:Laser_beam_(4134608343).jpg",
  "File:Life_almost_over.JPG",
  "Spirit possession",
  "Slender Man",
  "Zodiac Killer",
  "Sleep paralysis",
  "Timeline of the far future",
  "File:Jan_Brueghel_de_Oude_en_Peter_Paul_Rubens_-_Het_aards_paradijs_met_de_zondeval_van_Adam_en_Eva.jpg",
  "Haidinger's brush",
  "Diplopia",
  "Phosphene",
  "File:070309-moire-a5-a5-upward-movement.gif",
  "Dispersion (optics)",
  "Fluorescence",
  "Halo (optical phenomenon)",
  "Airglow",
  "File:Brocken_Spectre_at_California_Place.jpg",
  "Heiligenschein",
  "Lightning",
  "Mirage",
  "Iridescence",
  "File:Morpho didius Male Dos MHNT.jpg",
  "Shadow",
  "Finance",
  "File:A1 Houston Office Oil Traders on Monday.jpg",
  "File:American Progress (John Gast painting).jpg",
  "Democracy",
  "File:Justice-2060093_1920.jpg",
  "Corporatocracy",
  "Loab",
  "Tabletop game",
  "Greed",
  "Money",
];
