export const imageQueryStrings: string[] = [
  "Looney Tunes",
  "Fuck",
  "Award",
  // "Red",
  // "Black",
  // "Neil deGrasse Tyson",
  // "Donald Trump",
  // "Camera",
  // "Human",
  // "Evil",
  // "Devil",
  // "God",
  // "Angel",
  // "Truth",
  // "Dolly Parton",
  // "Jesus",
  // "Pornography",
  // "Kanye West",
  // "Marilyn Monroe",
  // "Elvis Presley",
  // "Barbie",
  // "IPhone",
  // "Racing",
  // "Blobject",
  // "Furniture",
  // "Tamagotchi",
  // "Earth",
  // "Mars",
  // "USS Doherty (DE-14)",
  // "Gaten Matarazzo",
  // "Memory management controller",
  // "Homosexuality in China",
  // "Socks and sandals",
  // "Heterodontosaurus",
  // "Karate",
  // "United States invasion of Grenada",
  // "CMLL World Middleweight Championship",
  // "Saint Anne",
  // "Gopnik",
  // "Interservice rivalry",
  // "SPP-1 underwater pistol",
  // "Chocolate bloom",
  // "Sloth bear",
  // "Willie Nelson",
  // "Lambda phage",
  // "Florence Y'all Water Tower",
  // "Embryo space colonization",
  // "Moon landing conspiracy theories",
  // "Black hairy tongue",
  // "Animals in space",
  // "Chick sexing",
  // "Toilets in Japan",
  // "Gurn",
  // "The Headington Shark",
  // "Electroencephalophone",
  // "Competitive eating",
  // "Diet Coke and Mentos eruption",
  // "Pillow Fight League",
  // "Rabbit show jumping",
  // "Nuclear weapon",
  // "Volcano",
  // "Church of Scientology",
  // "Galaxy",
  // "On the Mindless Menace of Violence",
  // "Novaya Zemlya effect",
];
